apiVersion: v1
kind: Service
metadata:
  name: knowledge-api
  labels:
    app: knowledge-api
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: knowledge-api
